[theme]
primaryColor = "#3498db"
backgroundColor = "#f0f0f0"
secondaryBackgroundColor = "#ffffff"
textColor = "#2c3e50"

[server]
maxUploadSize = 200
maxMessageSize = 200

[browser]
gatherUsageStats = false
